// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4KLa5VFNSJCx01aj3QbwFAjcgYWsqXVU',
    appId: '1:926998972809:web:a77b357ab48502a757f958',
    messagingSenderId: '926998972809',
    projectId: 'cw-w9-3083d',
    authDomain: 'cw-w9-3083d.firebaseapp.com',
    storageBucket: 'cw-w9-3083d.appspot.com',
    measurementId: 'G-FLFJ1HETRL',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXjq0Qyg8EzeRiTYG2KvvtJAGHQJXtY0M',
    appId: '1:926998972809:ios:fd5a476a1e39cb1d57f958',
    messagingSenderId: '926998972809',
    projectId: 'cw-w9-3083d',
    storageBucket: 'cw-w9-3083d.appspot.com',
    iosBundleId: 'com.example.clswk9',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXjq0Qyg8EzeRiTYG2KvvtJAGHQJXtY0M',
    appId: '1:926998972809:ios:fd5a476a1e39cb1d57f958',
    messagingSenderId: '926998972809',
    projectId: 'cw-w9-3083d',
    storageBucket: 'cw-w9-3083d.appspot.com',
    iosBundleId: 'com.example.clswk9',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4KLa5VFNSJCx01aj3QbwFAjcgYWsqXVU',
    appId: '1:926998972809:web:a55577c71292bbbf57f958',
    messagingSenderId: '926998972809',
    projectId: 'cw-w9-3083d',
    authDomain: 'cw-w9-3083d.firebaseapp.com',
    storageBucket: 'cw-w9-3083d.appspot.com',
    measurementId: 'G-C2E2MRPDS4',
  );
}
